/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Administrator
 * Created : 04/05/2013
 */

package io.leopard.test;

import org.junit.Test;

public class LeopardIntegrationTestsIntegrationTest extends IntegrationTests {

	@Test
	public void test() {

	}
}
