/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Administrator
 * Created : 04/08/2013
 */

package io.leopard.data.redis;

import io.leopard.data4j.redis.RedisAllImpl;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class RedisAllImplIntegrationTest {
	private static RedisAllImpl redis = new RedisAllImpl();

	@BeforeClass
	public static void init() {
		String[] serverList = "113.108.228.100:6301,113.108.228.100:6302".split(",");
		redis.setServerList(serverList);
		redis.init();
	}

	@AfterClass
	public static void destroy() {
		redis.destroy();
	}

	@Test
	public void set() {
		redis.set("key", "value");
	}
}
