/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Administrator
 * Created : 03/26/2013
 */

package io.leopard.data.redis;

import io.leopard.burrow.lang.Json;
import io.leopard.data4j.redis.Redis;
import io.leopard.data4j.redis.RedisHashImpl;

import java.util.List;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class RedisHashImplIntegrationTest {

	private static RedisHashImpl redis = new RedisHashImpl();

	@BeforeClass
	public static void init() {
		String[] serverList = "113.108.228.100:6301,113.108.228.100:6302".split(",");
		redis.setServerList(serverList);
		redis.setHashType("string");
		redis.init();

	}

	@AfterClass
	public static void destroy() {
		redis.destroy();
	}

	@Test
	public void mget() {

		Redis redis2 = redis;

		if (redis2 instanceof RedisHashImpl) {
			System.out.println("RedisHashImpl");
		}

		for (int i = 0; i < 10; i++) {
			redis.set("key:hctan" + i, "value:" + i);
		}
		String[] keys = new String[10];
		for (int i = 0; i < keys.length; i++) {
			keys[i] = "key:hctan" + i;
		}
		List<String> list = redis.mget(keys);
		Json.printList(list, "list");

	}

}
