/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Administrator
 * Created : 04/11/2013
 */

package io.leopard.web.permission;

import io.leopard.burrow.lang.Json;
import io.leopard.web4j.permission.Permission;
import io.leopard.web4j.permission.PermissionDaoMysqlImpl;
import io.leopard.web4j.permission.PermissionKey;

import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;


public class PermissionDaoMysqlImplIntegrationTest extends PermissionIntegrationTest {

	@Autowired
	private PermissionDaoMysqlImpl permissionDaoMysqlImpl;

	@Test
	public void get() {
		Permission permission = permissionDaoMysqlImpl.get(new PermissionKey("uri", "127.0.0.1"));
		Json.print(permission, "permission");
	}
}
